version: '3.3'
services:
  gitlab:
    container_name: gitlab
    image: registry.gitlab.cn/omnibus/gitlab-jh:latest
    restart: always
    hostname: '172.16.8.200'
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://172.16.8.200:10443'
        nginx['listen_port'] = 10443
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        letsencrypt['enable'] = false
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/server.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/server.key"
        nginx['ssl_ciphers'] = "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
        nginx['ssl_prefer_server_ciphers'] = "on"
        nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2 TLSv1.3"
        nginx['ssl_session_cache'] = "shared:SSL:10m" 
        nginx['redirect_http_to_https'] = true
        nginx['redirect_http_to_https_port'] = 10443
        nginx['client_max_body_size'] = '250m'
        nginx['worker_processes'] = 4
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = '503001318@qq.com'
        gitlab_rails['gitlab_email_display_name'] = 'gitlab'
        gitlab_rails['gitlab_email_reply_to'] = '503001318@qq.com'
        gitlab_rails['gitlab_email_subject_suffix'] = '[gitlab]'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.qq.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "503001318@qq.com"
        gitlab_rails['smtp_password'] = "ouwolliouwtsbiff"
        gitlab_rails['smtp_domain'] = "smtp.qq.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
    ports:
      - "0.0.0.0:10080:10080"
      - "0.0.0.0:10443:10443"
      - "0.0.0.0:2222:22"
    volumes:
      - /data/gitlab/config:/etc/gitlab:rw
      - /data/gitlab/logs:/var/log/gitlab:rw
      - /data/gitlab/data:/var/opt/gitlab:rw
    shm_size: '256m'
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
    deploy:
      resources:
         limits:
            cpus: "4.00"
            memory: 8G
         reservations:
            memory: 2G
    networks:
      gitlab:
        ipv4_address: 192.168.10.200
networks:
  gitlab:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
